# Generated by Django 3.2.7 on 2021-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
