# Generated by Django 3.2.7 on 2021-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetails',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
