# Generated by Django 3.2.7 on 2021-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_teamdetails_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerUrls',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRecentMatches',
            fields=[
                ('umpires', models.CharField(max_length=150)),
                ('result', models.TextField()),
                ('man_of_the_match', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField(default=None)),
                ('venue', models.TextField()),
                ('competing_team', models.CharField(max_length=150)),
                ('competing_team_logo', models.TextField()),
                ('first_innings', models.CharField(max_length=150)),
                ('second_innings', models.CharField(max_length=150)),
                ('match_status', models.CharField(max_length=20)),
            ],
        ),
    ]
