# Generated by Django 3.2.7 on 2021-09-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bannerurls_teamrecentmatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrecentmatches',
            name='team',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
