# Generated by Django 3.2.7 on 2021-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teamrecentmatches_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrecentmatches',
            name='team',
            field=models.CharField(max_length=10),
        ),
    ]
