# Generated by Django 3.2.7 on 2021-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_teamrecentmatches_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdetails',
            name='url',
        ),
        migrations.AddField(
            model_name='teamdetails',
            name='img',
            field=models.ImageField(default='default.img', upload_to='images'),
        ),
    ]
