# Generated by Django 3.2.7 on 2021-09-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210929_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdetails',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
